version: '3.8'

services:
  app:
    build: .
    ports:
      - '3000:3000'
    volumes:
      - .:/app
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: noughts_and_crosses
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U admin -d noughts_and_crosses']
      interval: 5s
      timeout: 5s
      retries: 5

  prisma:
    image: node:latest
    depends_on:
      postgres:
        condition: service_healthy
    command: >
      sh -c "npx prisma migrate dev --name initial_migration && npx prisma generate"
    working_dir: /app
    volumes:
      - .:/app

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
